# Generated by Django 3.2.4 on 2023-10-05 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('aPaterno', models.CharField(max_length=50)),
                ('aMaterno', models.CharField(max_length=50)),
                ('naciemiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especialidad')),
            ],
        ),
    ]
