# Generated by Django 3.2.4 on 2023-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0008_alter_usuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='aMaterno',
            new_name='apellido_materno',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='aPaterno',
            new_name='apellido_paterno',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nacimiento',
            new_name='fecha_de_nacimiento',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='idUser',
            new_name='idUsuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='alumno_user_groups', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='alumno_user_permissions', to='auth.Permission'),
        ),
    ]
