# Generated by Django 3.2.4 on 2023-11-24 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20231123_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='github_access_token',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='github_username',
        ),
    ]
