# Generated by Django 3.2.4 on 2023-11-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20231123_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='github_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
