# Generated by Django 3.2.4 on 2023-11-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20231124_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='nombre',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
