# Generated by Django 3.2.4 on 2024-01-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'Especialidades¿'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='sexo',
            options={'verbose_name_plural': 'Sexos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='facebook_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='facebook_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
