# Generated by Django 3.2.4 on 2024-01-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20240112_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='facebook_access_token',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='facebook_user_id',
        ),
    ]
